### ISSUE TITLE
[Feature request] Add links to plots

### ISSUE THREAD

**Issue by floriannadaud** [NeoCat/grafana-cal-heatmap-panel#1]
Hi,
It would be nice if we could configure links on the calendar.
Here is a proposal on how this could work
If you click on a dot you would be sent to a link defined in configuration. This link would be customisable with the time interval of the said dot.

In the option tab you would have a field where you can configure your link with at least two variables representing the timestamps interval of the dot. like `$ts_from` and `$ts_to`.

You would be able to configure a link like
`http://play.grafana.org/dashboard/db/apache-overview2?from=$ts_from&to=$ts_to`

This would redirect to 
`http://play.grafana.org/dashboard/db/apache-overview2?from=1481801799461&to=1481808999000`

I don't know if this is possible to implement but it seems like a nice feature to me.
Florian

**Comment by NeoCat** [comment]
Thanks for suggestion. I'll try implementing this.
